@startuml classes_Optics
skinparam classAttributeIconSize 0
set namespaceSeparator none
class "Beam" as src.objects.light_sources.Beam.Beam {
  -direction : tuple
  -point_one : tuple
  -point_two : tuple
  -ray_spacing : float
  -calculate_normal_direction()
  -create_rays()
  +__init__(point_one: tuple, point_two: tuple, ray_spacing: float, wavelength: float, intensity: float)
}
class "LightSource" as src.objects.light_sources.Base.LightSource {
  -intensity : float
  -position : tuple
  -rays : list
  -wavelength : float
  -white_light : bool
  +__init__(position: tuple, wavelength: float, intensity: float, white_light: bool)
  +get_emitted_rays()
  +get_intensity()
  +get_position()
  +get_wavelength()
  +get_white_light()
}
class "PointSource" as src.objects.light_sources.PointSource.PointSource {
  -RAY_ANGLE_INCREMENT_DEGREES : float
  +__init__(position: tuple, wavelength: float, intensity: float, angle_increment_degrees: float)
  +update_angle_increment_degrees(angle_increment_degrees)
}
class "Ray" as src.core.ray.Ray {
  +depth : int
  +direction
  +intensity : float
  +start_point
  +wavelength : int
  +__init__(start_point, direction, wavelength, intensity, depth)
}
class "Renderer" as src.GUI.renderer.Renderer {
  -LIGHT_RAY_COLOUR : tuple
  -LIGHT_SOURCE_COLOUR : tuple
  -LIGHT_SOURCE_RADIUS : int
  -background_color : tuple
  -clock
  -scene
  -screen
  +__init__()
  -render_beam_source(light_source: Beam)
  -render_light_ray(light_ray: Ray)
  -render_light_sources()
  -render_point_source(light_source)
  -render_scene()
}
class "Scene" as src.GUI.scene.Scene {
  -light_sources : list
  +__init__()
  +add_light_source(light_source: LightSource)
  +get_light_sources()
}
class "SingleRay" as src.objects.light_sources.SingleRay.SingleRay {
  -direction_point : tuple
  -ray_direction : tuple
  +__init__(position: tuple, direction_point: tuple, wavelength: float, intensity: float)
  +update_direction(new_direction_point)
}
src.objects.light_sources.Beam.Beam --|> src.objects.light_sources.Base.LightSource
src.objects.light_sources.PointSource.PointSource --|> src.objects.light_sources.Base.LightSource
src.objects.light_sources.SingleRay.SingleRay --|> src.objects.light_sources.Base.LightSource
' Light sources own their Rays
src.objects.light_sources.Base.LightSource "1" *-- "0..*" src.core.ray.Ray

' Renderer owns the Scene
src.GUI.renderer.Renderer *--> src.GUI.scene.Scene

' Scene is directed-associated with the light sources
src.GUI.scene.Scene "0..*" --> src.objects.light_sources.Base.LightSource
@enduml
